name: supervisor
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  cupertino_icons: ^1.0.2
  get_it: ^7.6.4
  injectable: ^2.3.2
  shared_preferences: ^2.2.2
  connectivity_plus: ^5.0.1
  dio: ^5.3.3
  retrofit: ^4.0.3
  intl: ^0.18.1
  json_annotation: ^4.8.1
  google_fonts: ^6.1.0
  go_router: ^12.1.1
  equatable: ^2.0.5
  bloc: ^8.1.2
  flutter_bloc: ^8.1.3
  flutter_secure_storage: ^9.0.0
  pretty_dio_logger: ^1.3.1
  dio_cache_interceptor: ^3.4.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  build_runner: ^2.4.6
  lint: ^2.2.0
  retrofit_generator: ^8.0.4
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  json_serializable: ^6.7.1
  bloc_test: ^9.1.5

flutter_gen:
  output: lib/generated/

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

flutter_intl:
  enabled: true

